version: '3'
volumes:
  mysql_data: {}
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    image: namthp99/chat-app_app:1.0
    # command: bundle exec puma -e production --pidfile /var/run/imp.pid
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      DATABASE_DEVELOPMENT_HOST: db
      RAILS_ENV: "development"
      REDIS_PRODUCTION_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      DB_CONNECTION: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_DB: chat-app_development
      MYSQL_HOST: db
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: ./docker/web/DockerFile
    image: namthp99/chat-app_web:1.0
    depends_on:
      - app
    ports:
      - 80:80
  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
