version: '3'
volumes:
  mysql_data: {}
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    image: namthp99/chat-app_app:1.0
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      DATABASE_DEVELOPMENT_HOST: db
      RAILS_ENV: "development"
      REDIS_DEVELOPMENT_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      DB_CONNECTION: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_DB: chat-app_development
      MYSQL_HOST: db
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  # cable:
  #   depends_on:
  #     - 'redis'
  #   build: .
  #   command: puma -p 28080 cable/config.ru
  #   ports:
  #     - '28080:28080'
  #   volumes:
  #     - '.:/app'
  #   env_file:
  #     - '.env'
